AWSTemplateFormatVersion: '2010-09-09'
Description: 'Guidance for Creating a Personalized Avatar with Amazon SageMaker: SO9281'

Parameters:
  ParameterVPCId:
    Description: ID of the AWS Virtual Private Cloud (VPC)
    Type: AWS::EC2::VPC::Id
  ParameterSubnet1Id:
    Description: SubnetId, for Availability Zone 1 in the region in your VPC
    Type: AWS::EC2::Subnet::Id
  ParameterSubnet2Id:
    Description: SubnetId, for Availability Zone 2 in the region in your VPC
    Type: AWS::EC2::Subnet::Id
  CreateS3BucketforSageMaker:
    Description: Do you want to create a S3 Bucket name like sagemaker-AWS::Region-AWS::AccountId
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

Conditions:
  CreateS3Bucket: !Equals
    - true
    - !Ref 'CreateS3BucketforSageMaker'

Resources:
  SageMakerBucket:
    Condition: CreateS3Bucket
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub sagemaker-${AWS::Region}-${AWS::AccountId}
      VersioningConfiguration:
        Status: Enabled
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  SageMakerExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: SageMakerStudioExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
                - codepipeline.amazonaws.com
                - codebuild.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: S3andMedicalImaging
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - "s3:GetObject"
                - "s3:PutObject"
                - "s3:DeleteObject"
                - "s3:ListBucket"
                - "s3:GetEncryptionConfiguration"
              Resource: "arn:aws:s3:::*"
            - Effect: Allow
              Action:
                - "iam:GetUser"
                - "iam:GetPolicy"
                - "iam:CreatePolicy"
                - "iam:GetRole"
                - "iam:CreateRole"
                - "iam:AttachRolePolicy"
              Resource: "*"
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess

  WorkshopDomain: 
    Type: AWS::SageMaker::Domain
    DependsOn: SageMakerExecutionRole
    Properties: 
      AuthMode: IAM
      DefaultUserSettings: 
        ExecutionRole: !GetAtt SageMakerExecutionRole.Arn
      DomainName: "SageMakerStudioWorkshopDomain"
      SubnetIds: 
        - !Ref ParameterSubnet1Id
        - !Ref ParameterSubnet2Id
      VpcId: !Ref ParameterVPCId
      
  DefaultUser:
    Type: AWS::SageMaker::UserProfile
    Properties: 
      DomainId: !Ref WorkshopDomain
      UserProfileName: sagemaker-user
    DependsOn: WorkshopDomain
    
      

